spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: 7hSYpeSHXZH5
    driver-class-name: oracle.jdbc.OracleDriver

  # JPA/Hibernate ayarları (opsiyonel)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# Server ayarları
server:
  port: 8080
